version: '3.1'

services:

    frontend:
      image: frontend-image
      restart: unless-stopped
      ports:
        - 8080:8080
      deploy:
        mode: replicated
        replicas: 3

    backend:
      image: backend-image
      restart: unless-stopped
      ports:
        - 3000:3000
      deploy:
        mode: replicated
        replicas: 3
      environment:
        DB_USERNAME: admin
        DB_PASSWORD: admin
        DB_DATABASE: zay
        DB_HOSTNAME: db
        PORT: 3000
      volumes:
        - shop:/app/share/backend

    db:
      image: mysql:8.0
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: zay
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
      ports:
        - 3306:3306
      deploy:
        mode: replicated
        replicas: 3
      volumes:
        - db:/app/share/db

    db-reset:
      image: db-reset
      restart: on-failure
      environment:
        DB_USERNAME: admin
        DB_PASSWORD: admin
        DB_DATABASE: zay
        DB_HOSTNAME: db
      depends_on:
        - db

volumes:
  shop:
  db:
