services:

    frontend:
      image: frontend-image
      restart: unless-stopped
      ports:
        - 8080:8080

    backend:
      image: backend-image
      restart: unless-stopped
      ports:
        - 3000:3000
      environment:
        DB_USERNAME: admin
        DB_PASSWORD: admin
        DB_DATABASE: zay
        DB_HOSTNAME: db
        PORT: 3000
      depends_on:
        db:
          condition: service_healthy
        db-reset:
          condition: service_completed_successfully
      volumes:
        - shop:/app/share/backend

    db:
      image: mysql:8.0
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: zay
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
      ports:
        - 3306:3306
      healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
        start_period: 10s
        interval: 5s
        timeout: 10s
        retries: 50
      volumes:
        - db:/app/share/db

    db-reset:
      image: db-reset
      restart: on-failure
      environment:
        DB_USERNAME: admin
        DB_PASSWORD: admin
        DB_DATABASE: zay
        DB_HOSTNAME: db
      depends_on:
        db:
          condition: service_healthy

volumes:
  shop:
  db:
